PRAGMA FOREIGN_KEYS = ON;

DROP TABLE IF EXISTS MEIAFINAL;
DROP TABLE IF EXISTS QUARTODEFINAL;
DROP TABLE IF EXISTS SERIE;
DROP TABLE IF EXISTS GOLO;
DROP TABLE IF EXISTS VISITANTE;
DROP TABLE IF EXISTS VISITADA;
DROP TABLE IF EXISTS CONTRATO;
DROP TABLE IF EXISTS JOGADOR;
DROP TABLE IF EXISTS JOGOPLAYOFF;
DROP TABLE IF EXISTS PLAYOFF;
DROP TABLE IF EXISTS FFINAL;
DROP TABLE IF EXISTS JOGOREGULAR;
DROP TABLE IF EXISTS JOGO;
DROP TABLE IF EXISTS POSICAO;
DROP TABLE IF EXISTS EQUIPA;

CREATE TABLE EQUIPA(
	IDEQUIPA INTEGER NOT NULL,
	NOME TEXT,
	CONSTRAINT EQUIPA_PK PRIMARY KEY (IDEQUIPA)
);

CREATE TABLE POSICAO(
	EQUIPA INTEGER,
	NUMERO INTEGER CHECK (NUMERO > 0),
	JORNADA INTEGER,
	PONTOS INTEGER CHECK (PONTOS >= 0) DEFAULT 0,
	VITORIAS INTEGER CHECK (VITORIAS >= 0),
	EMPATES INTEGER CHECK (EMPATES >= 0),
	DERROTAS INTEGER CHECK (DERROTAS >= 0),
	CONSTRAINT POSICAO_FK1 FOREIGN KEY (EQUIPA) REFERENCES EQUIPA(IDEQUIPA)
	CONSTRAINT POSICAO_PK PRIMARY KEY (NUMERO, JORNADA)
	
);


CREATE TABLE JOGO(
	IDJOGO INTEGER,
	DAT DATE,
	GOLOSVISITANTE INTEGER CHECK (GOLOSVISITANTE >= 0),
	GOLOSVISITADA INTEGER CHECK (GOLOSVISITADA >= 0),
	CONSTRAINT JOGO_PK PRIMARY KEY (IDJOGO)
);


CREATE TABLE JOGOREGULAR(
	JOGO INTEGER,
	JORNADA INTEGER CHECK (JORNADA > 0),
	CONSTRAINT JOGOREGULAR_PK PRIMARY KEY (JOGO),
	CONSTRAINT JOGOREGULAR_PK_FK1 FOREIGN KEY (JOGO) REFERENCES JOGO(IDJOGO)
);


CREATE TABLE FFINAL(
	IDFINAL INTEGER,
	CAMPEAO TEXT NOT NULL,
	CONSTRAINT FFINAL_PK PRIMARY KEY (IDFINAL)
);


CREATE TABLE PLAYOFF(
	IDPLAYOFF INTEGER,
	IDFINAL INTEGER,
	CONSTRAINT PLAYOFF_PK PRIMARY KEY (IDPLAYOFF),
	CONSTRAINT PLAYOFF_FK1 FOREIGN KEY (IDFINAL) REFERENCES FFINAL(IDFINAL)
);


CREATE TABLE JOGOPLAYOFF(
	JOGO INTEGER,
	PLAYOFF TEXT,
	CONSTRAINT JOGOPLAYOFF_PK PRIMARY KEY (JOGO),
	CONSTRAINT JOGOPLAYOFF_PK_FK1 FOREIGN KEY (JOGO) REFERENCES JOGO(IDJOGO),
	CONSTRAINT JOGOPLAYOFF_FK2 FOREIGN KEY (PLAYOFF) REFERENCES PLAYOFF(IDPLAYOFF)
);


CREATE TABLE JOGADOR(
	IDJOGADOR INTEGER,
	NOME TEXT NOT NULL,
	CONSTRAINT JOGAFOR_PK PRIMARY KEY (IDJOGADOR)
);


CREATE TABLE CONTRATO(
	JOGADOR INTEGER,
	EQUIPA INTEGER,
	DATAINICIO DATE,
	DATAFIM DATE,
	CONSTRAINT CONTRATO_PK PRIMARY KEY (JOGADOR, EQUIPA),
	CONSTRAINT CONTRATO_PK_FK1 FOREIGN KEY (JOGADOR) REFERENCES JOGADOR(IDJOGADOR),
	CONSTRAINT CONTRATO_PK_FK2 FOREIGN KEY (EQUIPA) REFERENCES EQUIPA(IDEQUIPA)
);


CREATE TABLE VISITADA(
	JOGO INTEGER,
	EQUIPA INTEGER,
	CONSTRAINT VISITADA_PK PRIMARY KEY (JOGO),
	CONSTRAINT VISITADA_PK_FK1 FOREIGN KEY (JOGO) REFERENCES JOGO(IDJOGO),
	CONSTRAINT VISITADA_FK2 FOREIGN KEY (EQUIPA) REFERENCES EQUIPA(IDEQUIPA)
);


CREATE TABLE VISITANTE(
	JOGO INTEGER,
	EQUIPA INTEGER,
	CONSTRAINT VISITANTE_PK PRIMARY KEY (JOGO),
	CONSTRAINT VISITANTE_PK_FK1 FOREIGN KEY (JOGO) REFERENCES JOGO(IDJOGO),
	CONSTRAINT VISITANTE_FK2 FOREIGN KEY (EQUIPA) REFERENCES EQUIPA(IDEQUIPA)
);


CREATE TABLE GOLO(
	IDGOLO INTEGER,
	JOGO INTEGER,
	JOGADOR INTEGER,
	EQUIPAAFAVOR INTEGER CHECK (EQUIPAAFAVOR > 0),
	MINUTO INTEGER CHECK (MINUTO >= 0),
	PERIODO INTEGER CHECK (PERIODO > 0),
	CONSTRAINT VISITANTE_PK PRIMARY KEY (IDGOLO),
	CONSTRAINT VISITANTE_FK1 FOREIGN KEY (JOGO) REFERENCES JOGO(IDJOGO),
	CONSTRAINT VISITANTE_FK2 FOREIGN KEY (JOGADOR) REFERENCES JOGADOR(IDJOGADOR)
);


CREATE TABLE SERIE(
	NUMERO INTEGER CHECK (NUMERO >=1 AND NUMERO<=6),
	VENCEDOR TEXT NOT NULL,
	PLAYOFF INTEGER,
	CONSTRAINT SERIE_PK PRIMARY KEY (NUMERO),
	CONSTRAINT JOGOPLAYOFF_FK2 FOREIGN KEY (PLAYOFF) REFERENCES PLAYOFF(IDPLAYOFF)
);


CREATE TABLE QUARTODEFINAL(
	JOGO INTEGER,
	NUMSERIE INTEGER,
	CONSTRAINT QUARTODEFINAL_PK PRIMARY KEY (JOGO),
	CONSTRAINT QUARTODEFINAL_PK_FK1 FOREIGN KEY (JOGO) REFERENCES JOGO(IDJOGO),
	CONSTRAINT QUARTODEFINAL_FK3 FOREIGN KEY (NUMSERIE) REFERENCES SERIE(NUMERO)
);


CREATE TABLE MEIAFINAL(
    JOGO INTEGER,
	NUMSERIE INTEGER,
	CONSTRAINT MEIAFINAL_PK PRIMARY KEY (JOGO),
	CONSTRAINT MEIAFINAL_PK_FK1 FOREIGN KEY (JOGO) REFERENCES JOGO(IDJOGO),
	CONSTRAINT MEIAFINAL_FK3 FOREIGN KEY (NUMSERIE) REFERENCES SERIE(NUMERO)
);