CREATE TRIGGER inserirPontos
AFTER INSERT ON POSICAO
FOR EACH ROW 
BEGIN 
	UPDATE POSICAO 
	SET PONTOS = 3*VITORIAS + EMPATES 
	WHERE POSICAO.NUMERO  = NEW.NUMERO and POSICAO.JORNADA = NEW.JORNADA; 
END;