CREATE TRIGGER inserirJornadaValida
BEFORE INSERT ON JOGOREGULAR
FOR  EACH ROW
WHEN NEW.JORNADA > 26
BEGIN
    SELECT RAISE(IGNORE);
END;


CREATE TRIGGER inserirSerieValida
BEFORE INSERT ON SERIE
FOR  EACH ROW
WHEN NEW.NUMERO > 6 
BEGIN
    SELECT RAISE(IGNORE);
END;