/* Teste da influência do Gatilho na Tabela Jogo */

-- Jogo Finalizado com 5-3
SELECT J.GOLOSVISITANTE, J.GOLOSVISITADA  FROM JOGO J
WHERE J.IDJOGO = 2021001;
INSERT INTO GOLO (IDGOLO,JOGO,JOGADOR,EQUIPAAFAVOR,MINUTO,PERIODO) VALUES
	 (5318,2021001,1001,2002,21,1);
-- Jogo Atualizado para 6-3
SELECT J.GOLOSVISITANTE, J.GOLOSVISITADA  FROM JOGO J
WHERE J.IDJOGO = 2021001;
INSERT INTO GOLO (IDGOLO,JOGO,JOGADOR,EQUIPAAFAVOR,MINUTO,PERIODO) VALUES
	 (5319,2021001,1001,2001,19,2);
-- Jogo Atualizado para 6-4
SELECT J.GOLOSVISITANTE, J.GOLOSVISITADA  FROM JOGO J
WHERE J.IDJOGO = 2021001;


/* Teste da influência do Gatilho na Tabela Posicao */

-- Tabela original (os novos golos não causam transtorno na tabela de classificação final)
SELECT P.JORNADA, P.EQUIPA, P.VITORIAS, P.EMPATES, P.DERROTAS, P.PONTOS  FROM POSICAO P;
INSERT INTO GOLO (IDGOLO,JOGO,JOGADOR,EQUIPAAFAVOR,MINUTO,PERIODO) VALUES
	 (5313,2021001,1001,2001,21,1);
-- Tabela quando o jogo ficou 6-5
SELECT P.JORNADA, P.EQUIPA, P.VITORIAS, P.EMPATES, P.DERROTAS, P.PONTOS  FROM POSICAO P;
INSERT INTO GOLO (IDGOLO,JOGO,JOGADOR,EQUIPAAFAVOR,MINUTO,PERIODO) VALUES
	 (5314,2021001,1001,2001,19,2);
-- Tabela quando o jogo ficou 6-6 (mudança para novo estado (1) na tabela)
SELECT P.JORNADA, P.EQUIPA, P.VITORIAS, P.EMPATES, P.DERROTAS, P.PONTOS  FROM POSICAO P;
INSERT INTO GOLO (IDGOLO,JOGO,JOGADOR,EQUIPAAFAVOR,MINUTO,PERIODO) VALUES
	 (5315,2021001,1001,2001,18,2);
-- Tabela quando o jogo ficou 6-7 (mudança para novo estado (2) na tabela)
SELECT P.JORNADA, P.EQUIPA, P.VITORIAS, P.EMPATES, P.DERROTAS, P.PONTOS  FROM POSICAO P;
INSERT INTO GOLO (IDGOLO,JOGO,JOGADOR,EQUIPAAFAVOR,MINUTO,PERIODO) VALUES
	 (5316,2021001,1001,2002,1,2);
-- Tabela quando o jogo ficou 7-7 (voltou para o estado (1) da tabela)
SELECT P.JORNADA, P.EQUIPA, P.VITORIAS, P.EMPATES, P.DERROTAS, P.PONTOS  FROM POSICAO P;
INSERT INTO GOLO (IDGOLO,JOGO,JOGADOR,EQUIPAAFAVOR,MINUTO,PERIODO) VALUES
	 (5317,2021001,1001,2002,2,2);
-- Tabela quando o jogo ficou 8-7 (equivalente a tabela original)
SELECT P.JORNADA, P.EQUIPA, P.VITORIAS, P.EMPATES, P.DERROTAS, P.PONTOS  FROM POSICAO P;