-- Ao adicionar um golo, alterar a pontuação do jogo
CREATE TRIGGER IF NOT EXISTS updateGameResult
AFTER INSERT ON GOLO
FOR EACH ROW 
WHEN (SELECT IDJOGO FROM JOGO) = NEW.JOGO
BEGIN
	UPDATE POSICAO 
	SET VITORIAS = VITORIAS + 1, EMPATES = EMPATES - 1
	WHERE ((SELECT j3.IDJOGO FROM JOGO j3 WHERE j3.GOLOSVISITANTE = j3.GOLOSVISITADA) = NEW.JOGO AND NEW.EQUIPAAFAVOR = POSICAO.EQUIPA
			AND (SELECT j3.IDJOGO FROM JOGO j3 WHERE j3.GOLOSVISITANTE = j3.GOLOSVISITADA) = (SELECT J2.JOGO FROM JOGOREGULAR j2) AND POSICAO.JORNADA >= (SELECT J2.JORNADA FROM JOGOREGULAR j2));
		
		
	UPDATE POSICAO 
	SET DERROTAS = DERROTAS + 1, EMPATES = EMPATES - 1
	WHERE ((SELECT j3.IDJOGO FROM JOGO j3 WHERE j3.GOLOSVISITANTE = j3.GOLOSVISITADA) = NEW.JOGO AND (SELECT E.IDEQUIPA FROM EQUIPA E, VISITADA INS, VISITANTE OUTS WHERE (E.IDEQUIPA = INS.EQUIPA AND INS.JOGO = NEW.JOGO AND NEW.EQUIPAAFAVOR <> E.IDEQUIPA) OR (E.IDEQUIPA = OUTS.EQUIPA AND OUTS.JOGO = NEW.JOGO AND NEW.EQUIPAAFAVOR <> E.IDEQUIPA)) = POSICAO.EQUIPA
			AND (SELECT j3.IDJOGO FROM JOGO j3 WHERE j3.GOLOSVISITANTE = j3.GOLOSVISITADA) = (SELECT J2.JOGO FROM JOGOREGULAR j2) AND POSICAO.JORNADA >= (SELECT J2.JORNADA FROM JOGOREGULAR j2));
		
		
	UPDATE POSICAO 
	SET EMPATES = EMPATES + 1, DERROTAS = DERROTAS - 1
	WHERE (((SELECT j3.IDJOGO FROM JOGO j3 WHERE j3.GOLOSVISITANTE = j3.GOLOSVISITADA +1) = NEW.JOGO AND NEW.EQUIPAAFAVOR = POSICAO.EQUIPA
			AND (SELECT j3.IDJOGO FROM JOGO j3 WHERE j3.GOLOSVISITANTE = j3.GOLOSVISITADA +1) = (SELECT J2.JOGO FROM JOGOREGULAR j2) AND POSICAO.JORNADA >= (SELECT J2.JORNADA FROM JOGOREGULAR j2)
		AND (SELECT e2.IDEQUIPA FROM EQUIPA e2, VISITADA v2 WHERE e2.IDEQUIPA = v2.EQUIPA AND v2.JOGO =NEW.JOGO) = NEW.EQUIPAAFAVOR)
		OR ((SELECT j3.IDJOGO FROM JOGO j3 WHERE j3.GOLOSVISITANTE + 1= j3.GOLOSVISITADA) = NEW.JOGO AND NEW.EQUIPAAFAVOR = POSICAO.EQUIPA
			AND (SELECT j3.IDJOGO FROM JOGO j3 WHERE j3.GOLOSVISITANTE +1 = j3.GOLOSVISITADA) = (SELECT J2.JOGO FROM JOGOREGULAR j2) AND POSICAO.JORNADA >= (SELECT J2.JORNADA FROM JOGOREGULAR j2)
		AND (SELECT e2.IDEQUIPA FROM EQUIPA e2, VISITANTE v2 WHERE e2.IDEQUIPA = v2.EQUIPA AND v2.JOGO =NEW.JOGO) = NEW.EQUIPAAFAVOR));
	
	UPDATE POSICAO 
	SET EMPATES = EMPATES + 1, VITORIAS = VITORIAS - 1
	WHERE (((SELECT j3.IDJOGO FROM JOGO j3 WHERE j3.GOLOSVISITANTE = j3.GOLOSVISITADA +1) = NEW.JOGO AND (SELECT E.IDEQUIPA FROM EQUIPA E, VISITADA INS, VISITANTE OUTS WHERE (E.IDEQUIPA = INS.EQUIPA AND INS.JOGO = NEW.JOGO AND NEW.EQUIPAAFAVOR <> E.IDEQUIPA) OR (E.IDEQUIPA = OUTS.EQUIPA AND OUTS.JOGO = NEW.JOGO AND NEW.EQUIPAAFAVOR <> E.IDEQUIPA)) = POSICAO.EQUIPA
			AND (SELECT j3.IDJOGO FROM JOGO j3 WHERE j3.GOLOSVISITANTE = j3.GOLOSVISITADA +1) = (SELECT J2.JOGO FROM JOGOREGULAR j2) AND POSICAO.JORNADA >= (SELECT J2.JORNADA FROM JOGOREGULAR j2)
		AND (SELECT e2.IDEQUIPA FROM EQUIPA e2, VISITADA v2 WHERE e2.IDEQUIPA = v2.EQUIPA AND v2.JOGO =NEW.JOGO) = NEW.EQUIPAAFAVOR)
		OR ((SELECT j3.IDJOGO FROM JOGO j3 WHERE j3.GOLOSVISITANTE + 1= j3.GOLOSVISITADA) = NEW.JOGO AND (SELECT E.IDEQUIPA FROM EQUIPA E, VISITADA INS, VISITANTE OUTS WHERE (E.IDEQUIPA = INS.EQUIPA AND INS.JOGO = NEW.JOGO AND NEW.EQUIPAAFAVOR <> E.IDEQUIPA) OR (E.IDEQUIPA = OUTS.EQUIPA AND OUTS.JOGO = NEW.JOGO AND NEW.EQUIPAAFAVOR <> E.IDEQUIPA)) = POSICAO.EQUIPA
			AND (SELECT j3.IDJOGO FROM JOGO j3 WHERE j3.GOLOSVISITANTE +1 = j3.GOLOSVISITADA) = (SELECT J2.JOGO FROM JOGOREGULAR j2) AND POSICAO.JORNADA >= (SELECT J2.JORNADA FROM JOGOREGULAR j2)
		AND (SELECT e2.IDEQUIPA FROM EQUIPA e2, VISITANTE v2 WHERE e2.IDEQUIPA = v2.EQUIPA AND v2.JOGO =NEW.JOGO) = NEW.EQUIPAAFAVOR));
	
	
	UPDATE POSICAO 
	SET PONTOS = 3*VITORIAS + EMPATES;
		
	UPDATE JOGO 
	SET GOLOSVISITANTE = GOLOSVISITANTE + 1
	WHERE (IDJOGO = NEW.JOGO AND NEW.EQUIPAAFAVOR = (SELECT E.IDEQUIPA  FROM VISITANTE V, EQUIPA E, JOGO J, GOLO G
														WHERE (E.IDEQUIPA = V.EQUIPA AND V.JOGO = J.IDJOGO AND G.JOGO = J.IDJOGO)));
	UPDATE JOGO
	SET GOLOSVISITADA = GOLOSVISITADA + 1
	WHERE (IDJOGO = NEW.JOGO AND NEW.EQUIPAAFAVOR = (SELECT E.IDEQUIPA  FROM VISITADA V, EQUIPA E, JOGO J, GOLO G
														WHERE (E.IDEQUIPA = V.EQUIPA AND V.JOGO = J.IDJOGO AND G.JOGO = J.IDJOGO)));
END;