.mode columns
.headers on
.nullvalue NULL

SELECT GAME_1P.JOGO, WINNERS.NOME AS VENCEDOR_COMEBACK
FROM (SELECT TMP.JOGO1 AS JOGO,
		IFNULL(TMP.NOME1,
		(SELECT X.NOME
		FROM EQUIPA X, VISITANTE Y, JOGO Z
		WHERE X.IDEQUIPA = Y.EQUIPA AND Y.JOGO = Z.IDJOGO AND Z.IDJOGO = TMP.JOGO1)) AS NOME1,
		TMP.GOLOS1,
		IFNULL(TMP.NOME2,
		(SELECT X.NOME
		FROM EQUIPA X, VISITADA Y, JOGO Z
		WHERE X.IDEQUIPA = Y.EQUIPA AND Y.JOGO = Z.IDJOGO AND Z.IDJOGO = TMP.JOGO2)) AS NOME2,
		TMP.GOLOS2
FROM (SELECT IFNULL(T.JOGO,V.JOGO) AS JOGO1,
T.NOME AS NOME1,
		IFNULL(T.GOLOS,0) AS GOLOS1, IFNULL(V.JOGO,T.JOGO) AS JOGO2,
V.NOME AS NOME2,
		IFNULL(V.GOLOS,0) AS GOLOS2
FROM (SELECT J.IDJOGO AS JOGO, E.NOME AS NOME, COUNT(*) AS GOLOS
	FROM GOLO G, JOGO J, VISITANTE O, EQUIPA E
	WHERE J.IDJOGO = G.JOGO AND J.IDJOGO = O.JOGO  AND O.EQUIPA = E.IDEQUIPA
	AND E.IDEQUIPA = G.EQUIPAAFAVOR AND G.PERIODO = 1
	GROUP BY 1) T
FULL OUTER JOIN (SELECT J.IDJOGO AS JOGO, E.NOME AS NOME, COUNT(*) AS GOLOS
	FROM GOLO G, JOGO J, VISITADA I, EQUIPA E
	WHERE J.IDJOGO = G.JOGO AND J.IDJOGO = I.JOGO  AND I.EQUIPA = E.IDEQUIPA
	AND E.IDEQUIPA = G.EQUIPAAFAVOR AND G.PERIODO = 1
	GROUP BY 1) V ON T.JOGO = V.JOGO) TMP
ORDER BY 1) GAME_1P,
(SELECT J.IDJOGO AS JOGO, E.NOME AS NOME
	FROM JOGO J, VISITANTE O, EQUIPA E
	WHERE J.IDJOGO = O.JOGO  AND O.EQUIPA = E.IDEQUIPA AND J.GOLOSVISITANTE>J.GOLOSVISITADA
	UNION ALL
	SELECT J.IDJOGO AS JOGO, E.NOME AS NOME
	FROM JOGO J, VISITADA I, EQUIPA E
	WHERE J.IDJOGO = I.JOGO  AND I.EQUIPA = E.IDEQUIPA AND J.GOLOSVISITANTE<J.GOLOSVISITADA 
	ORDER BY 1) WINNERS
WHERE WINNERS.JOGO = GAME_1P.JOGO AND ((WINNERS.NOME = GAME_1P.NOME1 AND GAME_1P.GOLOS1<GAME_1P.GOLOS2)
OR (WINNERS.NOME = GAME_1P.NOME2 AND GAME_1P.GOLOS1>GAME_1P.GOLOS2))