.mode columns
.headers on
.nullvalue NULL

DROP VIEW IF EXISTS INTERVENIENTES;
CREATE VIEW INTERVENIENTES AS
SELECT q.NUMSERIE, e.NOME as EQUIPA1, e2.NOME as EQUIPA2
FROM QUARTODEFINAL q, JOGO j, VISITADA vada, VISITANTE vante, EQUIPA e, EQUIPA e2 
WHERE q.JOGO = j.IDJOGO and vada.JOGO = j.IDJOGO and vante.JOGO = j.IDJOGO and e.IDEQUIPA = vada.EQUIPA and vante.EQUIPA = e2.IDEQUIPA  and e.NOME < e2.NOME 
UNION
SELECT m.NUMSERIE, e.NOME as EQUIPA1, e2.NOME as EQUIPA2
FROM MEIAFINAL m, JOGO j, VISITADA vada, VISITANTE vante, EQUIPA e, EQUIPA e2 
WHERE m.JOGO = j.IDJOGO and vada.JOGO = j.IDJOGO and vante.JOGO = j.IDJOGO and e.IDEQUIPA = vada.EQUIPA and vante.EQUIPA = e2.IDEQUIPA and e.NOME > e2.NOME; 

DROP VIEW IF EXISTS VENCEDORES;
CREATE VIEW VENCEDORES AS
SELECT q.NUMSERIE, e.NOME, COUNT(*) as JOGOSVENCIDOS
FROM QUARTODEFINAL q, JOGO j, EQUIPA e, GOLO g 
WHERE q.JOGO = j.IDJOGO and g.JOGO = j.IDJOGO and e.IDEQUIPA = g.EQUIPAAFAVOR
GROUP BY 2
UNION
SELECT m.NUMSERIE, e.NOME, COUNT(*) as JOGOSVENCIDOS
FROM MEIAFINAL m, JOGO j, EQUIPA e, GOLO g 
WHERE m.JOGO = j.IDJOGO and g.JOGO = j.IDJOGO and e.IDEQUIPA = g.EQUIPAAFAVOR
GROUP BY 2;

DROP VIEW IF EXISTS JOGOSPORSERIE;
CREATE VIEW JOGOSPORSERIE AS
SELECT q.NUMSERIE, count(*) as numjogos
FROM QUARTODEFINAL q 
group by 1
UNION 
SELECT m.NUMSERIE, count(*) as numjogos
FROM MEIAFINAL m  
group by 1;

SELECT v.numserie as SERIE, i.equipa1, i.equipa2, j.numjogos as JOGOSJOGADOS, v.nome as VENCEDOR, v.jogosvencidos
FROM VENCEDORES v, INTERVENIENTES i, JOGOSPORSERIE j
WHERE v.numserie = i.numserie and j.numserie = v.numserie