.mode columns
.headers on
.nullvalue NULL

SELECT T.PERIODO, ROUND(AVG(T.NGOLOS),2) AS MEDIAGOLOS
FROM (SELECT J.IDJOGO AS NOME, G.PERIODO AS PERIODO, COUNT(*) as NGOLOS
FROM GOLO G, JOGO J
WHERE J.IDJOGO = G.JOGO 
GROUP BY 1) T
GROUP BY 1