.mode columns
.headers on
.nullvalue NULL

SELECT E.NOME, COUNT(*) AS VITORIAS_EM_CASA
FROM EQUIPA E, JOGO J, VISITADA V
WHERE E.IDEQUIPA = V.EQUIPA  AND V.JOGO = J.IDJOGO AND J.GOLOSVISITANTE < J.GOLOSVISITADA 
GROUP BY 1
ORDER BY 2 DESC
LIMIT 1